### PR TITLE
add bike and booking

### PR DESCRIPTION
**Pull request by Chocolateraisins**
Hi guys, added models with all the attributes. Please have a look and give feedback.

### CODE REVIEW

**Comment by victorking1988** [comment]
looks good to me

**Comment by codenas** [comment]
Looks good,  but can we add destroy dependents? i.e. Destroy bikes when user is deleted.

**Comment by Chocolateraisins** [comment]
Okay, will have a look.

**Comment by victorking1988** [comment]
you're welcome

**Comment by Chocolateraisins** [comment]
Thank you guys for your collaboration. this would have been possible without you. The open source communtiy at its best! Amazing work!!!!

**Pull request merged**
